### ISSUE TITLE
Full API support?

### ISSUE THREAD

**Issue by tomatohater** [cgoldberg/sauceclient#12]
Hey @cgoldberg,

I made some big updates to my branch of sauceclient:
[https://github.com/tomatohater/sauceclient/tree/support-for-full-api](https://github.com/tomatohater/sauceclient/tree/support-for-full-api)

 it now supports the full Sauce API set. All the tests are mocked, so they run without actually hitting Sauce. Tests have 100% coverage.

TravisCI is wired up and passing:
[https://travis-ci.org/tomatohater/sauceclient](https://travis-ci.org/tomatohater/sauceclient)

A few things... I added requests and six as dependencies... just easier. Also, and more importantly, there are a few (not not many) backwards incompatible changes. There are still a few more things I'm cleaning up (some docs and utility functions).

I'd love to get your feedback before I submit a big pull request.

**Comment by cgoldberg** [comment]
@tomatohater 

thanks for this.  overall, I am +1 these changes.  I do have a few comments on the code, so go ahead and submit a PR and I will add a review.

as for backwards compatibility...  meh.. maintaining the deprecated methods and announcing a migration plan sounds tedious for a such a small utility like this :)   I think we should release the new naming and other changes as a new major revision (1.0?).   (I have a few things I'd also like to get into a 1.0 release)

**Comment by tomatohater** [comment]
Thanks for merging the PR.
